packaging_format = 2

id = "libreddit"
name = "Libreddit"
description.en = "Libre alternative to Reddit"
description.fr = "Alternative libre à Reddit"

version = "0.30.1~ynh3"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://libreddit.spike.codes/"
demo = "https://libreddit.spike.codes/"
code = "https://github.com/spikecodes/libreddit"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/spikecodes/libreddit/releases/download/v0.30.1/libreddit"
        sha256 = "9bba0a2bc4fc18d2f27d3793359f700921ebe1812c59623d83e04d2e39cfec28"
        extract = false
        in_subdir = false
        rename = "libreddit"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
