packaging_format = 2

id = "libreddit"
name = "Libreddit"
description.en = "Libre alternative to Reddit"
description.fr = "Alternative libre à Reddit"

version = "0.30.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://libreddit.spike.codes/"
demo = "https://libreddit.spike.codes/"
code = "https://github.com/spikecodes/libreddit"

[integration]
yunohost = ">= 11.1.14"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
[resources.sources]
    [resources.sources.main]
    url = "https://github.com/spikecodes/libreddit/releases/download/v0.30.0/libreddit"
    sha256 = "46f7424d963af88428c7863010c8a20d6c5791b6425495abe6439a4838d65427"
    extract = false
    in_subdir = false
    rename = "libreddit"
